### ISSUE TITLE
GPU VMWARE attestation

### ISSUE THREAD

**Issue by pegahnikbakht** [ccc-certifier-framework/certifier-framework-for-confidential-computing#230]
Hi, 

Are there any docs about how the GPU attestation report can be extracted from VMWARE and the report contains which information or fields and also how it should be verified? 

Thanks in advance,
Pegah

**Comment by rgerganov** [comment]
You can refer to [this document](https://github.com/vmware-research/certifier-framework-for-confidential-computing/blob/main/Doc/Certifier-Nvidia-H100GPU-Support.pdf) about our design on how Nvidia H100 GPUs are going to be supported in the Certifier Framework. The implementation is still in progress.

**Comment by gapisback** [comment]
9/25/2024: Re-visited with the team.

@yelvmw said that the implementation is still in progress; hasn't been implemented, yet. So there is no further documentation available.

For now, nothing further to do w.r.t docs, so we agreed to close out this issue.
