### ISSUE TITLE
simple_app generate_symmetric_key() fails w/--public_key_alg=rsa-3072 --auth_symmetric_key_alg=aes-128-cbc-hmac-sha256

### ISSUE THREAD

**Issue by gapisback** [ccc-certifier-framework/certifier-framework-for-confidential-computing#234]
Testing with test case run_test-crypto_algorithms added by PR https://github.com/vmware-research/certifier-framework-for-confidential-computing/pull/232 , simple_app fails to succeed when run with this pair of crypto-algorithms: `--public_key_alg=rsa-3072 --auth_symmetric_key_alg=aes-128-cbc-hmac-sha256`

```
run_example.sh: simple_app: Running run_app_by_name_as_server_talk_to_Cert_Service
+ set +x
run_example.sh: Public-key algorithm: '--public_key_alg=rsa-3072', Authenticated Symmetric-key algorithm: '--auth_symmetric_key_alg=aes-128-cbc-hmac-sha256'

+ /home/agurajada/Code/certifier-framework-for-confidential-computing/sample_apps/simple_app/example_app.exe --data_dir=./app2_data/ --operation=cold-init --measurement_file=example_app.measurement --policy_store_file=policy_store --public_key_alg=rsa-3072 --auth_symmetric_key_alg=aes-128-cbc-hmac-sha256 --print_all=true
measurement file='example_app.measurement', public_key_alg='rsa-3072', authenticated_symmetric_key_alg='aes-128-cbc-hmac-sha256
generate_symmetric_key() error, line 1095, unsupported encryption algorithm: 'aes-128-cbc-hmac-sha256'
cold_init() error, line 1306, Can't generate symmetric key
main() error, line 432, cold-init failed
```

While developing the list of supported Authenticated symmetric-key algorithms, during code review of PR #232  , it was confirmed that this`Enc_method_aes_128_cbc_hmac_sha256` should be a valid crypto-algorithm name.

But testing shows some other deficiencies. Either we have to fix the logic in `generate_symmetric_key()` or re-visit whether this "aes-128-cbc-hmac-sha256" is a valid Authenticated symmetric-key algorithm.

**Comment by jlmucb** [comment]
This is by design.  AES-128 is not a reasonable authenticated encryption algorithm for an RSA-3072 based key.
