### ISSUE TITLE
Few test commands are not working when I follow CI documentation

### ISSUE THREAD

**Issue by hemanth5555** [ccc-certifier-framework/certifier-framework-for-confidential-computing#240]
Hello,
I was able to install the dependencies of certifier framework properly, but when I tried to run few test commands, they are failing with similar issue
Command - ./CI/scripts/test.sh test-run_example-simple_app_python
<img width="1417" alt="Screenshot 2024-04-16 at 2 36 49 AM" src="https://github.com/ccc-certifier-framework/certifier-framework-for-confidential-computing/assets/43142609/d98d1f53-78f7-483d-baa8-9743db99ab6a">
This issue is happening with multiple test commands

**Comment by gapisback** [comment]
HI, @hemanth5555 - I think there is one step missing in the INSTALL.md instructions.

On my Ubuntu Linux, I see this header installed:

```
agurajada-Linux-Vm:[14] $   ll /usr/include/uuid
total 20
-rw-r--r--  1 root  4023 Apr  9 08:32 uuid.h
```

I don't recall how it got there but did the following:

1. uninstalled this package using: `$ sudo apt remove uuid-dev`

2. Then, I re-installed this package using: `$ sudo apt-get install uuid-dev`

(You may have to do `$ sudo apt-get update -y` first.)

After I ran [2], I confirmed that this exists:

```
agurajada-Linux-Vm:[16] $   ll /usr/include/uuid
total 20
-rw-r--r--  1 root  4023 Apr  9 08:32 uuid.h
```

Can you please try [2] and see if this package installs correctly for you? And then, does this unblock your builds and test?

If this works for you, let us know. I will update the INSTALL.md and build.yml to explicitly install these headers. I suspect on our CI machines, these headers got installed somehow through a combination of installs done for other packages.
