### ISSUE TITLE
Inquiry of source code location for the feature, "Application Upgrade"

### ISSUE THREAD

**Issue by bokdeuk-jeong** [ccc-certifier-framework/certifier-framework-for-confidential-computing#247]
https://github.com/ccc-certifier-framework/certifier-framework-for-confidential-computing/blob/main/Doc/CertifierFramework.pdf
I am looking into the slide on page 8. Could you point me which source files correspond to the feature, "Application Upgrade"? Providing the source code location of an example with that would be much appreciated. 
Thank you.

**Comment by gapisback** [comment]
Discussed with @jlmucb in monthly meeting. He has info that can answer this question. John will update this space to communicate requested info to @bokdeuk-jeong

**Comment by bokdeuk-jeong** [comment]
@jlmucb 
John, I'm leaving this message to check if you are available to respond.

**Comment by jlmucb** [comment]
I'm back on now
